version = 0.1

[default.deploy.parameters]
stack_name = "integration-incident-intelligence-servicenow"
resolve_s3 = true
s3_prefix = "integration-incident-intelligence-servicenow"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "ap-south-1"
